spring.application.name=rural-reach

#server.port = 5646

spring.datasource.url=jdbc:postgresql://localhost:5433/rural_reach
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

#spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/schema.sql
spring.liquibase.enabled=true

#logging.level.org.springframework.aop=DEBUG

spring.main.banner-mode=off

#springdoc.api-docs.path=/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html